services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nfgda-service:
    build:
      context: ./nfgda_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - ./nfgda_output:/nfgda_output
      - ./processed_data:/processed_data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - ./nfgda_output:/nfgda_output
      - ./processed_data:/processed_data